# Python CircleCI 2.0 configuration file
# Details: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1
      
      # Service dependencies
      - image: mongo

    working_directory: ~/cn-db

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  deploy-job:
    docker:
      - image: cn-db
    working_directory: /cn-db
    steps:
      - run:
          name: Install requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: Deploy
          command: ping $SERVER_IP

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master