# Python CircleCI 2.0 configuration file
# Details: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1
      
      # Service dependencies
      - image: mongo

    working_directory: ~/cn-db

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Python Fixtures
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python main.py

  deploy-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/cn-db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Deploy
          command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ~/cn-db root@$SERVER_IP:/apps/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master