# Python CircleCI 2.0 configuration file
# Details: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1
      
      # Service dependencies
      - image: mongo

    working_directory: ~/cn-db

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  deploy-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/cn-db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Deploy
          command: ping $SERVER_IP -c 4
      - run:
          name: Where am I 2
          command: pwd
      - run:
          name: List of stuff 3
          command: ls -la ~/cn-db

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master